add Christine
betamore/fewd-pull-request-exercise pull request #87
Opened 2018-09-23 23:55 UTC by chriscyber

2018-09-25 19:18 UTC, tkraak requested changes

2018-09-25 19:18 UTC, tkraak commented on README.md
> +  [github.com/chriscyber] (https://github.com/chriscyber)
There is no space between `[github.com/chriscyber] and (https://github.com/chriscyber)`.

2018-09-25 19:38 UTC, chriscyber commented on README.md
> +  [github.com/chriscyber] (https://github.com/chriscyber)
Now i see the comment!...thanks.

2018-09-26 18:11 UTC, tkraak approved these changes

2018-09-26 18:40 UTC, merged